#!/bin/bash
BACKUPDIR=~/backup
HOMEDIR="/home/sali/public_html"
BACKUPFILE=backup.`date +%F`.tar.gz
THRESHOLD=3
if [ ! -e $BACKUPDIR ];
then
echo Creating backup directory it does not exist
mkdir ~/backup
exit 0
else
COUNT=`ls $BACKUPDIR/home.* | wc -l`
fi
if [ $COUNT -le $THRESHOLD ];
then
tar -czvf $BACKUPDIR/$BACKUPFILE $HOMEDIR
if [ $? != 0 ]; then echo Problems creating backup file; fi
fi
